### ISSUE TITLE
Trade with multiple execution is not showing correct data.

### ISSUE THREAD

**Issue by wezzybytes** [briansrls/Robinhood-for-Google-Finance#11]
I have a few trades with multiple executions, and the CSV output looks like following:

```
Commission,Purchase price per share,Shares,Transaction type,Symbol,Date purchased,
0.12,2.49,9.0,sell,[SYMBOL_A],2016-03-09T20:56:43.636000Z,
0.12,2.49,9.0,sell,[SYMBOL_A],2016-03-09T20:56:43.636000Z,
0.12,2.49,9.0,sell,[SYMBOL_A],2016-03-09T20:56:43.636000Z,
0.12,2.49,5.0,sell,[SYMBOL_A],2016-03-09T20:56:43.635000Z,
0.12,2.49,9.0,sell,[SYMBOL_A],2016-03-09T20:56:43.635000Z,
0.12,2.49,9.0,sell,[SYMBOL_A],2016-03-09T20:56:43.635000Z,
0.16,1.53,5.0,sell,[SYMBOL_B],2016-03-17T19:59:00.355000Z,
0.16,1.53,7.0,sell,[SYMBOL_B],2016-03-17T19:59:00.355000Z,
0.16,1.53,7.0,sell,[SYMBOL_B],2016-03-17T19:59:00.354000Z,
0.16,1.53,7.0,sell,[SYMBOL_B],2016-03-17T19:59:00.353000Z,
0.16,1.53,13.0,sell,[SYMBOL_B],2016-03-17T19:59:00.352000Z,
0.16,1.53,10.0,sell,[SYMBOL_B],2016-03-17T19:59:00.352000Z,
0.16,1.53,13.0,sell,[SYMBOL_B],2016-03-17T19:59:00.351000Z,
0.16,1.53,13.0,sell,[SYMBOL_B],2016-03-17T19:59:00.350000Z,
```
The fee/commission is not charged per execution.

Also, should the CSV output show all executions?  Normally when we import data in other tools, we usually enter each trade (containing cumulative quantity and average price paid).

**Comment by briansrls** [comment]
I believe I understand the issue.  You're saying that although there were multiple executions for one trade, the fees are not charged per execution.

I'm not confident I understand how this works on an execution level, but from reading around I see SEC forces brokerages to have "Best Execution" rules.  This means that brokerages need to have the clients interest in mind when routing executions for one trade.  

I would like to see a source showing that commission is not charged per execution.  
From https://www.sec.gov/files/OCIE%20Risk%20Alert%20-%20IA%20Best%20Execution.pdf:

> An adviser must execute securities transactions
> for clients in such a manner that the client’s total costs or proceeds in
> each transaction are the most favorable under the circumstances.

> In directing brokerage, an adviser should consider the full range and
> quality of a broker-dealer’s services including, among other things, the
> value of research provided as well as execution capability,
> commission rate, financial responsibility, and responsiveness to the adviser. As the Commission has
> stated, “the determinative factor [in an adviser’s best execution analysis] is not the lowest possible
> commission cost but whether the transaction represents the best qualitative execution for the 
> managed account.
  
The case may be that commission is paid per execution, but this commission column is actually an aggregate of all of the executions for that trade.  In other words, they would only write these executions when the trade has been completed or cancelled and use the same variable for all entries.

We could aggregate different executions, but I'm not sure how that would work if they were out of order.  For example if your data was instead:

```
0.16,1.53,5.0,sell,[SYMBOL_B],2016-03-17T19:59:00.355000Z,
0.16,1.53,7.0,sell,[SYMBOL_B],2016-03-17T19:59:00.355000Z,
0.16,1.53,7.0,sell,[SYMBOL_B],2016-03-17T19:59:00.354000Z,
0.12,2.49,9.0,sell,[SYMBOL_A],2016-03-09T20:56:43.636000Z,
0.12,2.49,9.0,sell,[SYMBOL_A],2016-03-09T20:56:43.636000Z,
0.12,2.49,9.0,sell,[SYMBOL_A],2016-03-09T20:56:43.636000Z,
0.12,2.49,5.0,sell,[SYMBOL_A],2016-03-09T20:56:43.635000Z,
0.12,2.49,9.0,sell,[SYMBOL_A],2016-03-09T20:56:43.635000Z,
0.12,2.49,9.0,sell,[SYMBOL_A],2016-03-09T20:56:43.635000Z,
0.16,1.53,7.0,sell,[SYMBOL_B],2016-03-17T19:59:00.353000Z,
0.16,1.53,13.0,sell,[SYMBOL_B],2016-03-17T19:59:00.352000Z,
0.16,1.53,10.0,sell,[SYMBOL_B],2016-03-17T19:59:00.352000Z,
0.16,1.53,13.0,sell,[SYMBOL_B],2016-03-17T19:59:00.351000Z,
0.16,1.53,13.0,sell,[SYMBOL_B],2016-03-17T19:59:00.350000Z,
```

How could we aggregate SYMBOL_B, meaning how could we know they belong to the same trade?

Thanks for your post and I would appreciate your feedback because I am quite out of my area when it comes to these topics.

**Comment by briansrls** [comment]
Data is now imported by trade, not by execution.  This means that commissions should always be accurate.  Let me know if you find otherwise.
