### ISSUE TITLE
Add support for 2FA

### ISSUE THREAD

**Issue by CameronBanga** [briansrls/Robinhood-for-Google-Finance#6]
Went and tried to use this, but unable to with a Robinhood account that uses 2FA. 

Enter my username, password, but receive an ```Invalid username or password.  Try again.``` error. After entering my password, I'm texted a 2FA code, so it looks like my creds validate. Just no way to enter a 2FA code.

**Comment by briansrls** [comment]
I actually didn't know robinhood supported 2FA, that may be a problem though as we're at the mercy of the robinhood API  [here](https://github.com/Jamonek/Robinhood).  I (or someone) will have to play around and see if they've implemented anything to handle 2FA.

**Comment by CameronBanga** [comment]
@briansrls I took a look at a few other investment/stock management apps that support Robinhood, and it seems like all have some sort of various issue with Robinhood 2FA. It looks like a couple _do_ support it, but they seem to require I validate my 2FA code every time I want to make an API call and refresh my portfolio, etc, which is kinda a pain.

So their 2FA work may be a little rough.

**Comment by briansrls** [comment]
@CameronBanga could you link someone that does support it? It's a good first step

**Comment by CameronBanga** [comment]
@briansrls Sure, they were iOS apps!

https://appsto.re/us/Us10E.i
https://appsto.re/us/foW9_.i

**Comment by he-zhe** [comment]
Not sure if this would help.  But I just created a pull request to the api to support MFA.
[#20](https://github.com/Jamonek/Robinhood/pull/20)

**Comment by briansrls** [comment]
@he-zhe thanks for that, I'll have to check it out when I get home.

**Comment by briansrls** [comment]
@he-zhe I've integrated the changes, and everything is working fine!  I ran in to some issues with regards to using python2 vs python3, so before you commit to the other repo I would check to see which version they prefer using, as I think they may want it to be compatible with both.  You can see my version of robinhood.py to see any changes I made to make this work.

**Comment by briansrls** [comment]
Issue resolved until further notice

**Comment by he-zhe** [comment]
@briansrls Thanks a lot!  I tried both Python 2 and 3 on the api repo.  And both of them gave errors (Python 2 for urllib.request;  Python3 for raw_input).  I was confused by this so I didn't change anything other than the login function.  I hope they will fix this soon.  Thanks again for your work!  It makes monitoring my portfolio much easier.

**Comment by briansrls** [comment]
@he-zhe If you're interested you can see where I implemented some fixes [here](https://github.com/briansrls/Robinhood-for-Google-Finance/blob/master/Robinhood.py#L98), in python 2 the correct call is simply urllib.urlencode, while in python 3 it was changed to urllib.parse.urlencode.  Another example is [here](https://github.com/briansrls/Robinhood-for-Google-Finance/blob/master/Robinhood.py#L93), where in python 2 grabbing input was called raw_input, while it's now just called input in python 3.

Another instance was [here](https://github.com/briansrls/Robinhood-for-Google-Finance/blob/master/Robinhood.py#L7), where in python3 and python2 the library seemed to be restructured a bit so that urlretrieve is now a part of urllib.request instead of just urllib.  

I hope these examples helped clear up any confusion.
